/**
 * Regenerates src/bot/clues/data/cluedb.ts from the content pack — the id-keyed
 * answer DB for the 66 easy clues (all named "Clue scroll"; only the obj id
 * distinguishes them, and params aren't client-readable, so this table is
 * load-bearing).
 *   bun tools/clues/gen-cluedb.ts            # rewrite the file
 *   bun tools/clues/gen-cluedb.ts --check    # exit 1 if the committed file is stale
 * Content root: $CONTENT_DIR or ~/code/rs2b2t-content.
 *
 * Resolution:
 *   obj ids  — pack/obj.pack (`<id>=<name>`), covers the 6 dig caskets too.
 *   npc names — `name=` in scripts/**.npc configs; canonical files win over the
 *               scripts/_unpack/<rev> decompiled dumps.
 * Hard cases (see the maps below): vague003 (no coord in config) and _sailor
 * (abstract base; the completing npc is captain_tobias via an npc_type guard).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { decodeCoord } from '../nav/stairsParse.js';
import { buildClueDb, parseClueObjs, parseEnum, parseTalkMappings, type TalkMapping } from './cluesParse.js';

const CONTENT = process.env.CONTENT_DIR ?? join(homedir(), 'code', 'rs2b2t-content');
const OUT = 'src/bot/clues/data/cluedb.ts';
const TRAIL = join(CONTENT, 'scripts', 'minigames', 'game_trail', 'configs');

// vague003 ("search the drawers upstairs") carries no trail_coord; drawers.rs2
// handles it as a search-loc at this tile — decodes to (2574,3326,1), the Fishing
// Guild area (matches the navTargets 'vague003 Fishing Guild' label).
const VAGUE003_COORD = '1_40_51_14_62';

// _sailor is an abstract base npc with no config name; the sailor that hands over
// vague012 is guarded by `npc_type = captain_tobias` in sailors.rs2.
const NPC_ALIAS: Record<string, string> = { _sailor: 'captain_tobias' };

function filesUnder(root: string, ext: string): string[] {
    return (readdirSync(root, { recursive: true }) as string[])
        .filter(f => f.endsWith(ext))
        .map(f => join(root, f))
        .sort();
}

/** pack/obj.pack: `<id>=<name>` → name → id. */
function loadObjIds(): Map<string, number> {
    const text = readFileSync(join(CONTENT, 'pack', 'obj.pack'), 'utf8');
    const out = new Map<string, number>();
    for (const raw of text.split('\n')) {
        const m = /^(\d+)=(\S+)$/.exec(raw.trim());
        if (m) {
            out.set(m[2], Number(m[1]));
        }
    }
    return out;
}

/** debugname → display name from every .npc config. Canonical configs are
 *  applied after the _unpack dumps so they win; the abstract-npc aliases are
 *  folded in last. */
function loadNpcDisplayNames(): Map<string, string> {
    const files = filesUnder(join(CONTENT, 'scripts'), '.npc');
    const unpack = files.filter(f => f.includes('/_unpack/'));
    const canonical = files.filter(f => !f.includes('/_unpack/'));
    const names = new Map<string, string>();
    for (const f of [...unpack, ...canonical]) {
        let cur: string | null = null;
        for (const raw of readFileSync(f, 'utf8').split('\n')) {
            const line = raw.trim();
            const head = /^\[([a-z0-9_]+)\]$/.exec(line);
            if (head) {
                cur = head[1];
            } else if (cur && line.startsWith('name=')) {
                names.set(cur, line.slice('name='.length));
            }
        }
    }
    for (const [from, to] of Object.entries(NPC_ALIAS)) {
        const display = names.get(to);
        if (display !== undefined) {
            names.set(from, display);
        }
    }
    return names;
}

function generate(): string {
    const enumText = readFileSync(join(TRAIL, 'trail_easy.enum'), 'utf8');
    const objText = readFileSync(join(TRAIL, 'trail_easy.obj'), 'utf8');
    const talk: TalkMapping[] = filesUnder(join(CONTENT, 'scripts'), '.rs2').flatMap(f => parseTalkMappings(readFileSync(f, 'utf8')));

    const { db, caskets } = buildClueDb({
        clueNames: parseEnum(enumText),
        objs: parseClueObjs(objText),
        objIds: loadObjIds(),
        talk,
        npcDisplay: loadNpcDisplayNames(),
        specials: { trail_clue_easy_vague003: { type: 'search', coord: decodeCoord(VAGUE003_COORD) } }
    });

    const ids = Object.keys(db).map(Number).sort((a, b) => a - b);
    const talkCount = ids.filter(id => db[id].type === 'talk').length;
    console.log(`clues=${ids.length} talk=${talkCount} caskets=${Object.keys(caskets).length}`);

    const clueLines = ids.map(id => `    ${id}: ${JSON.stringify(db[id])}`);
    const casketLines = Object.keys(caskets)
        .map(Number)
        .sort((a, b) => a - b)
        .map(id => `    ${id}: ${JSON.stringify(caskets[id])}`);

    return [
        '/* eslint-disable */',
        '// GENERATED by tools/clues/gen-cluedb.ts — do not edit.',
        '// Regenerate: bun tools/clues/gen-cluedb.ts   (drift gate: --check)',
        "import type { ClueRow } from '#/bot/clues/types.js';",
        '',
        'export const CLUE_DB: Record<number, ClueRow> = {',
        clueLines.join(',\n'),
        '};',
        '',
        '// casket obj id → casket obj name; lets the solver recognise a held casket.',
        'export const CASKET_IDS: Record<number, string> = {',
        casketLines.join(',\n'),
        '};',
        ''
    ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
    let current = '';
    try {
        current = readFileSync(OUT, 'utf8');
    } catch {
        // missing file = drift
    }
    if (current !== fresh) {
        console.error(`STALE: ${OUT} does not match the content pack — run: bun tools/clues/gen-cluedb.ts`);
        process.exit(1);
    }
    console.log(`ok: ${OUT} matches the content pack`);
} else {
    writeFileSync(OUT, fresh);
    console.log(`wrote ${OUT}`);
}
