import { readFileSync, writeFileSync } from 'node:fs';
import type { ScriptMeta } from '#/bot/runtime/ScriptRegistry.js';
import type { SettingDef } from '#/bot/runtime/Settings.js';

const OUT = 'docs/SCRIPTS.md';

function anchor(text: string): string {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9 _-]/g, '')
        .replace(/ /g, '-');
}

// a bare | ends the cell
function cell(text: string): string {
    return text.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
}

function settingRow(key: string, def: SettingDef): string {
    const bounds = def.min !== undefined || def.max !== undefined ? ` (${def.min ?? ''}–${def.max ?? ''})` : '';
    const options = def.options ? `${def.label ? ' — ' : ''}one of: ${def.options.join(', ')}` : '';
    const note = cell(`${def.label ?? ''}${options}`);
    return `| \`${key}\` | ${def.type}${bounds} | \`${cell(JSON.stringify(def.default))}\` | ${note} |`;
}

export function renderScriptDocs(metas: ScriptMeta[]): string {
    const byCategory = new Map<string, ScriptMeta[]>();
    for (const meta of [...metas].sort((a, b) => a.name.localeCompare(b.name))) {
        const category = meta.category ?? 'Uncategorised';
        byCategory.set(category, [...(byCategory.get(category) ?? []), meta]);
    }
    const categories = [...byCategory.keys()].sort();

    const lines: string[] = [
        '<!-- GENERATED by tools/gen-scriptdocs.ts — do not edit. -->',
        '<!-- Regenerate: bun run gen:scriptdocs   (drift gate: bun tools/gen-scriptdocs.ts --check) -->',
        '',
        '[Manual](README.md) › Bundled scripts',
        '',
        '# Bundled scripts',
        '',
        `The client ships **${metas.length} scripts** across ${categories.length} categories. They double as worked`,
        'examples of the [scripting API](API.md) — the source for each is under',
        '[`src/bot/scripts/`](../src/bot/scripts/).',
        '',
        'Settings listed here are the parameters the panel exposes before you start a script.',
        '',
        '## Contents',
        '',
        ...categories.map(category => `- [${category}](#${anchor(category)}) — ${byCategory.get(category)!.length}`),
        ''
    ];

    for (const category of categories) {
        lines.push(`## ${category}`, '');
        for (const meta of byCategory.get(category)!) {
            lines.push(`### ${meta.name}`, '', meta.description, '');
            if (meta.tags?.length) {
                lines.push(`Tags: ${meta.tags.map(tag => `\`${tag}\``).join(', ')}`, '');
            }
            const schema = meta.settingsSchema;
            if (schema && Object.keys(schema).length > 0) {
                lines.push('| Setting | Type | Default | Notes |', '|---|---|---|---|');
                for (const [key, def] of Object.entries(schema)) {
                    lines.push(settingRow(key, def));
                }
                lines.push('');
            }
        }
    }

    lines.push('## See also', '', '- [Manual index](README.md)', '- [Scripting API](API.md) — the surface these are written against', '- [Running locally](RUNNING.md#running-a-bot) — how to start one', '');
    return lines.join('\n');
}

if (import.meta.main) {
    const { GlobalRegistrator } = await import('@happy-dom/global-registrator');
    GlobalRegistrator.register();
    const { ScriptRegistry } = await import('#/bot/runtime/ScriptRegistry.js');
    await import('#/bot/scripts/index.js');

    const metas = ScriptRegistry.list();
    const fresh = renderScriptDocs(metas);
    console.log(`scripts=${metas.length}`);

    if (process.argv.includes('--check')) {
        let current = '';
        try {
            current = readFileSync(OUT, 'utf8');
        } catch {
            current = '';
        }
        if (current !== fresh) {
            console.error(`STALE: ${OUT} does not match the registry — run: bun run gen:scriptdocs`);
            process.exit(1);
        }
        console.log(`ok: ${OUT} matches the registry`);
    } else {
        writeFileSync(OUT, fresh);
        console.log(`wrote ${OUT}`);
    }
}
