// Generate src/client/io/{ClientProt,ServerProt}.ts from the engine's prot tables, so a
// revision bump is a regenerate-and-review instead of ~150 hand-transcribed opcodes.
//
//   bun tools/gen-prot.ts            # write the files
//   bun test test/io/protDrift.test.ts   # fail if they drift from the engine
//
// The engine declares `static readonly NAME = new XGameProt(<id>, <length>);`. Server
// opcodes live in two files: ServerGameProt.ts and ServerGameZoneProt.ts.

import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

// rs2b0t's historical names for symbols the engine calls something else. Keys are the
// engine's name, values are ours. Renaming ours would touch every call site in Client.ts.
const ALIAS: Record<string, string> = {
    IF_SETTAB: 'IF_SETICON',
    IF_SETTAB_ACTIVE: 'IF_SHOWICON',
    RESET_CLIENT_VARCACHE: 'VARP_SYNC',
    LOC_MERGE: 'P_LOCMERGE',
    REPORT_ABUSE: 'SEND_SNAPSHOT'
};

type Prot = { name: string; id: number; length: number };

function parse(source: string): Prot[] {
    const re = /static readonly ([A-Z0-9_]+) = new [A-Za-z]+\((-?\d+),\s*(-?\d+)\)/g;
    const out: Prot[] = [];
    for (const m of source.matchAll(re)) {
        out.push({ name: ALIAS[m[1]] ?? m[1], id: Number(m[2]), length: Number(m[3]) });
    }
    return out;
}

function renderEnum(name: string, prots: Prot[]): string {
    const body = prots.map(p => `    ${p.name} = ${p.id},`).join('\n');
    return `export const enum ${name} {\n${body}\n}\n`;
}

function renderSizes(prots: Prot[]): string {
    const sizes = new Array(256).fill(0);
    for (const p of prots) {
        sizes[p.id] = p.length;
    }
    const rows: string[] = [];
    for (let i = 0; i < 256; i += 10) {
        rows.push('    ' + sizes.slice(i, i + 10).join(', ') + ',');
    }
    return `export const ServerProtSizes = [\n${rows.join('\n')}\n];\n`;
}

export function generateProt(engineDir: string): { client: string; server: string } {
    const read = (p: string) => readFileSync(join(engineDir, p), 'utf8');

    const client = parse(read('src/network/game/client/ClientGameProt.ts'));
    const server = [
        ...parse(read('src/network/game/server/ServerGameProt.ts')),
        ...parse(read('src/network/game/server/ServerGameZoneProt.ts'))
    ];

    const header = '// GENERATED by tools/gen-prot.ts from the engine. Do not edit by hand.\n\n';

    return {
        client: header + renderEnum('ClientProt', client),
        server: header + renderEnum('ServerProt', server) + '\n' + renderSizes(server)
    };
}

if (import.meta.main) {
    const engine = process.env.ENGINE_DIR ?? join(homedir(), 'code', 'rs2b2t-engine');
    const { client, server } = generateProt(engine);
    writeFileSync('src/client/io/ClientProt.ts', client);
    writeFileSync('src/client/io/ServerProt.ts', server);
    console.log('wrote src/client/io/{ClientProt,ServerProt}.ts');
}
