import { readFileSync, writeFileSync } from 'node:fs';

import { buildMaze, parseJm2Locs, solveRoute, MAZE_SHRINE, MAZE_SPAWNS, edgeKey } from '../src/bot/api/maze/mazeGraph.js';

function parseArgs(): { map: string; out: string } {
    const args = process.argv.slice(2);
    let map = new URL('../test/api/maze/fixtures/m45_71.jm2', import.meta.url).pathname;
    let out = 'src/bot/api/maze/mazeRoutes.ts';
    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--map') { map = args[++i]; }
        else if (args[i] === '--out') { out = args[++i]; }
        else { console.error(`unknown argument: ${args[i]}`); process.exit(2); }
    }
    return { map, out };
}

const { map, out } = parseArgs();
const locs = parseJm2Locs(readFileSync(map, 'utf8'));
const g = buildMaze(locs);
const routes = MAZE_SPAWNS.map(spawn => ({ spawn, doors: solveRoute(g, spawn) }));

function render(spawn: { x: number; z: number }, doors: { x: number; z: number }[]): string {
    const onRoute = new Set(doors.map(d => `${d.x},${d.z}`));
    const rows: string[] = [];
    for (let z = g.maxz; z >= g.minz; z--) {
        let row = '';
        for (let x = g.minx; x <= g.maxx; x++) {
            if (x === MAZE_SHRINE.x && z === MAZE_SHRINE.z) { row += 'X'; }
            else if (x === spawn.x && z === spawn.z) { row += 'S'; }
            else if (onRoute.has(`${x},${z}`)) { row += 'D'; }
            else if (g.wallEdge.has(edgeKey(x, z, x + 1, z)) || g.wallEdge.has(edgeKey(x, z, x, z + 1))) { row += '#'; }
            else { row += '.'; }
        }
        rows.push(row);
    }
    return rows.join('\n');
}

for (const r of routes) {
    console.log(`\n=== spawn (${r.spawn.x},${r.spawn.z}) — ${r.doors.length} doors ===`);
    console.log(render(r.spawn, r.doors));
}

const body = routes.map(r => `    { spawn: { x: ${r.spawn.x}, z: ${r.spawn.z} }, doors: [${r.doors.map(d => `{ x: ${d.x}, z: ${d.z} }`).join(', ')}] }`).join(',\n');
const file = `// GENERATED by tools/maze-derive.ts — do not edit by hand.
// Regenerate: bun tools/maze-derive.ts

export interface MazeRoute {
    spawn: { x: number; z: number };
    doors: { x: number; z: number }[];
}

export const MAZE_ROUTES: MazeRoute[] = [
${body}
];
`;
writeFileSync(out, file);
console.log(`\nwrote ${out}`);
