import { expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { execFileSync, spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { checkComments, checkDocCap } from '../../tools/lint-prose-extras.js';

function fixture(name: string, body: string): string {
    const dir = mkdtempSync(join(tmpdir(), 'prose-'));
    const path = join(dir, name);
    writeFileSync(path, body);
    return path;
}

test('a file at the cap passes', () => {
    const path = fixture('ok.md', 'line\n'.repeat(150));
    expect(checkDocCap([path])).toEqual([]);
});

test('a file over the cap is reported once', () => {
    const path = fixture('big.md', 'line\n'.repeat(151));
    const found = checkDocCap([path]);
    expect(found.length).toBe(1);
    expect(found[0].check).toBe('doc-cap');
    expect(found[0].message).toContain('151');
});

test('a generated file is exempt', () => {
    const path = fixture('gen.md', `<!-- GENERATED by tools/x.ts -->\n${'line\n'.repeat(900)}`);
    expect(checkDocCap([path])).toEqual([]);
});

test('a rationale comment without a Why: tag is reported', () => {
    const path = fixture('why.ts', '// The cache is skipped because the lock is held.\nexport const a = 1;\n');
    const found = checkComments([path]);
    expect(found.some(f => f.check === 'why-tag')).toBe(true);
});

test('a rationale comment carrying a Why: tag passes', () => {
    const path = fixture('tagged.ts', '// Why: the cache is skipped because the lock is held.\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'why-tag')).toEqual([]);
});

test('a comment block over two lines is reported', () => {
    const path = fixture('block.ts', '// one\n// two\n// three\nexport const a = 1;\n');
    const found = checkComments([path]);
    expect(found.some(f => f.check === 'comment-block')).toBe(true);
});

test('a two-line comment block passes', () => {
    const path = fixture('short.ts', '// one\n// two\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a JSDoc block with two payload lines passes', () => {
    const path = fixture('jsdoc.ts', '/**\n * one\n * two\n */\nexport const a = 1;\n');
    expect(checkComments([path]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a JSDoc block with three payload lines is reported', () => {
    const path = fixture('jsdoc-long.ts', '/**\n * one\n * two\n * three\n */\nexport const a = 1;\n');
    const found = checkComments([path]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('3-line');
});

test('a usage block of runnable commands is not a comment block', () => {
    const body = ['// Usage:', '//   bun tools/coaltrucks-test.ts --phase cross --speed 300 --minutes 3   # proves the log balance level', '//   bun tools/coaltrucks-test.ts --minutes 45                            # full uncheated loop', '//   ENGINE_DIR=... sh tools/deploy-local.sh   # once', 'export const a = 1;', ''].join('\n');
    expect(checkComments([fixture('usage.ts', body)])).toEqual([]);
});

test('a redeploy-then-run usage block is not a comment block', () => {
    const body = [
        '// Usage:',
        '//   ~/redeploy.sh   # botclient with RandomEventGuardian + maze fix',
        '//   ~/redeploy.sh && HEADED=1 bun tools/varrock-sewer-web-370-live.ts',
        '//   HEADED=1 SHIP_352=1 bun tools/nav-script-routes-live.ts',
        '//   then: HEADED=1 bun tools/nav-tele-smoke.ts',
        'export const a = 1;',
        ''
    ].join('\n');
    expect(checkComments([fixture('redeploy.ts', body)])).toEqual([]);
});

test('a labelled command wrapped over continuation lines is one usage line', () => {
    const body = [
        '// Ideal (inventory pre-loaded, max stats) — mid-quest smoke only (proven PASS):',
        '//   HEADED=1 bun tools/aio-quest-test.ts http://localhost:8890 ew1 elemental_workshop 15 \\',
        "//     'knife:1,hammer:1,bronze_pickaxe:1' \\",
        "//     max Lobster 'speed 300' '2716,3481'",
        'export const a = 1;',
        ''
    ].join('\n');
    expect(checkComments([fixture('wrapped.ts', body)])).toEqual([]);
});

test('a prose run longer than the header allowance is still a comment block', () => {
    const body = [
        '// The cache is skipped while the lock is held.',
        '// Callers then re-read the manifest.',
        '// A stale entry would otherwise survive the swap:',
        '//   bun tools/x.ts',
        'export const a = 1;',
        ''
    ].join('\n');
    const found = checkComments([fixture('longheader.ts', body)]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
});

test('a rationale block of the same length is still a comment block', () => {
    const body = ['// The cache is skipped while the lock is held.', '// Callers then re-read the manifest.', '// A stale entry would otherwise survive the swap.', 'export const a = 1;', ''].join('\n');
    const found = checkComments([fixture('rationale.ts', body)]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('3-line');
});

function emitted(header: string): string {
    return [
        '/* eslint-disable */',
        header,
        '',
        '/** Monster display name → the drop names its table can yield.',
        ' *  The rows are sorted because the consumer binary-searches them.',
        ' *  Direct drops and always-drops are folded together.',
        ' *  Sub-tables are resolved in place. */',
        'export const a = 1;',
        ''
    ].join('\n');
}

test('a generated source file yields no comment-block finding', () => {
    const path = fixture('gen-block.ts', emitted('// GENERATED by tools/x.ts — do not edit.'));
    expect(checkComments([path]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a generated source file yields no why-tag finding', () => {
    const path = fixture('gen-why.ts', emitted('/* Generated by tools/x.ts */'));
    expect(checkComments([path]).filter(f => f.check === 'why-tag')).toEqual([]);
});

test('the same file without a generated marker reports both', () => {
    const path = fixture('hand.ts', emitted('// Hand-written header — do not edit.'));
    const checks = checkComments([path]).map(f => f.check);
    expect(checks).toContain('comment-block');
    expect(checks).toContain('why-tag');
});

test('a doc-path citation does not count toward the block payload', () => {
    const body = [
        '/**',
        ' * The vault keys credentials by profile so a restore never crosses accounts.',
        ' * Slots are recycled in flex order.',
        ' * @see docs/reference/api-game.md#world-primitives',
        ' */',
        'export const a = 1;',
        ''
    ].join('\n');
    expect(checkComments([fixture('cite-jsdoc.ts', body)]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a bare doc-path backlink does not count toward the block payload', () => {
    const body = ['// docs/reference/multibox.md#profile-vault', '// The vault stores one credential set per profile.', '// Slots are recycled in flex order.', 'export const a = 1;', ''].join('\n');
    expect(checkComments([fixture('cite-bare.ts', body)]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('every citation shape is exempt', () => {
    const body = [
        '// docs/reference/multibox.md#profile-vault',
        '// @see docs/reference/api-game.md#world-primitives',
        '/**',
        ' * @see docs/how-to/run-locally.md',
        ' */',
        '// (#215)',
        '// #160',
        '// (#445).',
        'export const a = 1;',
        ''
    ].join('\n');
    expect(checkComments([fixture('cite-shapes.ts', body)])).toEqual([]);
});

test('a line merely mentioning docs is not a citation', () => {
    const body = ['// one line of prose', '// the docs cover this in more detail', '// a third line of prose', 'export const a = 1;', ''].join('\n');
    const found = checkComments([fixture('cite-word.ts', body)]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('3-line');
});

test('a citation-only block is never a finding', () => {
    const body = ['// docs/reference/multibox.md#slots', '// docs/reference/multibox.md#login-coordination', '// docs/decisions/architecture.md#layers', 'export const a = 1;', ''].join('\n');
    expect(checkComments([fixture('cite-only.ts', body)])).toEqual([]);
});

test('a block whose payload lines are all Why:-tagged is not a comment block', () => {
    const body = [
        '// Why: the bank booth op is "Use-quickly" on this stand.',
        '// Why: the loc query is empty for a tick after a region change.',
        '// Why: a journal colour tag collapses to a space.',
        '// Why: sub-tables are resolved in place.',
        'export const a = 1;',
        ''
    ].join('\n');
    expect(checkComments([fixture('all-tagged.ts', body)]).filter(f => f.check === 'comment-block')).toEqual([]);
});

test('a mixed block of tagged and untagged lines is still a comment block', () => {
    const body = [
        '// Why: the bank booth op is "Use-quickly" on this stand.',
        '// Why: the loc query is empty for a tick after a region change.',
        '// The panel repaints on every frame.',
        '// Callers then re-read the manifest.',
        'export const a = 1;',
        ''
    ].join('\n');
    const found = checkComments([fixture('mixed-tagged.ts', body)]).filter(f => f.check === 'comment-block');
    expect(found.length).toBe(1);
    expect(found[0].message).toContain('4-line');
});

test('a lint directive is never reported', () => {
    const path = fixture('directive.ts', '// eslint-disable-next-line no-restricted-imports -- the adapter is not ready\n// @ts-expect-error upstream types are wrong because the overload is missing\n// prettier-ignore\nexport const a = 1;\n');
    expect(checkComments([path])).toEqual([]);
});

test('CLI skips deleted paths and checks untracked files while respecting ignores', () => {
    const dir = mkdtempSync(join(tmpdir(), 'prose-cli-'));
    try {
        mkdirSync(join(dir, 'docs'));
        mkdirSync(join(dir, 'tools'));
        writeFileSync(join(dir, 'README.md'), '# Project\n');
        writeFileSync(join(dir, 'docs/deleted.md'), 'line\n'.repeat(151));
        writeFileSync(join(dir, 'tools/existing.ts'), 'export const value = 1;\n');
        writeFileSync(join(dir, '.gitignore'), 'docs/ignored.md\n');
        execFileSync('git', ['init', '-q', dir]);
        execFileSync('git', ['-C', dir, 'add', '.']);
        rmSync(join(dir, 'docs/deleted.md'));
        writeFileSync(join(dir, 'docs/new file.md'), 'line\n'.repeat(151));
        writeFileSync(join(dir, 'docs/ignored.md'), 'line\n'.repeat(151));
        writeFileSync(join(dir, 'tools/new.ts'), '// one\n// two\n// three\nexport const value = 1;\n');
        const result = spawnSync(process.execPath, [resolve(import.meta.dir, '../../tools/lint-prose-extras.ts')], { cwd: dir, encoding: 'utf8' });
        expect(result.status).toBe(1);
        expect(result.stderr).toBe('');
        expect(result.stdout).toContain('docs/new file.md:151');
        expect(result.stdout).toContain('tools/new.ts:1');
        expect(result.stdout).not.toContain('deleted.md');
        expect(result.stdout).not.toContain('ignored.md');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});
